"""empty message

Revision ID: 32157fe96184
Revises: da026af577cd
Create Date: 2016-07-19 15:54:06.382899

"""

# revision identifiers, used by Alembic.
revision = '32157fe96184'
down_revision = 'da026af577cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'buildings_user_id_fkey', 'buildings', type_='foreignkey')
    op.create_foreign_key(None, 'buildings', 'players', ['player_id'], ['id'])
    op.drop_column('buildings', 'hexagon')
    op.drop_column('buildings', 'edge')
    op.drop_column('buildings', 'user_id')
    op.drop_column('buildings', 'row')
    op.add_column('roads', sa.Column('player_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'roads_user_id_fkey', 'roads', type_='foreignkey')
    op.create_foreign_key(None, 'roads', 'players', ['player_id'], ['id'])
    op.drop_column('roads', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roads', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'roads', type_='foreignkey')
    op.create_foreign_key(u'roads_user_id_fkey', 'roads', 'players', ['user_id'], ['id'])
    op.drop_column('roads', 'player_id')
    op.add_column('buildings', sa.Column('row', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('edge', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('buildings', sa.Column('hexagon', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.create_foreign_key(u'buildings_user_id_fkey', 'buildings', 'players', ['user_id'], ['id'])
    op.drop_column('buildings', 'player_id')
    op.drop_column('buildings', 'index')
    ### end Alembic commands ###
