"""empty message

Revision ID: b3259ccd0601
Revises: 32157fe96184
Create Date: 2016-07-28 15:08:15.751215

"""

# revision identifiers, used by Alembic.
revision = 'b3259ccd0601'
down_revision = '32157fe96184'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('building', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'building')
    ### end Alembic commands ###
