"""empty message

Revision ID: da026af577cd
Revises: adfcc501e960
Create Date: 2016-07-19 13:50:45.082586

"""

# revision identifiers, used by Alembic.
revision = 'da026af577cd'
down_revision = 'adfcc501e960'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roads', 'color')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roads', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
